name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    # runs-on: ubuntu-18.04
    runs-on: macos-latest
    # runs-on: windows-2019
    steps:
    - uses: actions/checkout@v2
    # - name: Generate CMake Code
    # run: cmake -DCMAKE_BUILD_TYPE=Release .. && cmake ..
    #   run: cd Build && cmake -G "Visual Studio 14 2015" -A Win32 -DCMAKE_BUILD_TYPE=Release .. && cmake ..
    # - name: Assign Solution file
    #   run: devenv StepMania.sln /Build Release
    - name: Install brew
      run: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
    - name: Install yasm
      run: brew install cmake yasm
    - name: Genrate CMake code
      run: cd Build && cmake -G 'Xcode' -DCMAKE_BUILD_TYPE=Release .. && cmake ..
    - name: make
      run: make
