name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: Genrate CMake code
      run: cd Build && cmake -G 'Unix Makefiles' -DCMAKE_BUILD_TYPE=Release ..
    - name: make
      run: make
