name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    # runs-on: ubuntu-18.04
    runs-on: macos-latest
    # runs-on: windows-2019
    steps:
    - uses: actions/checkout@v2
    # - name: Generate CMake Code
    # run: cmake -DCMAKE_BUILD_TYPE=Release .. && cmake ..
    #   run: cd Build && cmake -G "Visual Studio 14 2015" -A Win32 -DCMAKE_BUILD_TYPE=Release .. && cmake ..
    # - name: Assign Solution file
    #   run: devenv StepMania.sln /Build Release
    #- name: Install brew
    #  run: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
    - name: Pre Process, Update Brew
      run: brew update
    - name: Pre Process, Upgrade packages
      run: brew upgrade cmake && brew install yasm && xcode-select --install
    - name: Update submodules
      run: git submodule update --init
    - name: Generate CMake code
      run: cd Build && cmake .. -G 'Xcode' -DCMAKE_BUILD_TYPE=${BUILD_TYPE} -DCMAKE_C_COMPILER="/Applications/Xcode_11.4.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang" -DCMAKE_CXX_COMPILER="/Applications/Xcode_11.4.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++" -DWITH_FFMPEG_JOBS=2
    - name: Compile using xcodebuild
      run: cd Build && cmake --build . --parallel 2
